// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/v1/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/[id].patch').default>>>>
    }
    '/api/v1/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/index.post').default>>>>
    }
    '/api/v1/users/validation/requests/CreateUserRequest': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/validation/requests/CreateUserRequest').default>>>>
    }
    '/api/v1/users/validation/requests/UpdateUserRequest': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/validation/requests/UpdateUserRequest').default>>>>
    }
    '/api/v1/users/validation/response/UserCollection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/validation/response/UserCollection').default>>>>
    }
    '/api/v1/users/validation/response/UserResource': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/validation/response/UserResource').default>>>>
    }
    '/api/_hub/**:feature': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/@nuxthub+core@0.8.27_db0@0.3.2_@libsql+client@0.15.9_better-sqlite3@11.10.0_drizzle-orm@0.44._oita7dv4ruuvcqadrtwvvu6voa/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/[...feature]').default>>>>
    }
    '/api/_hub': {
      'head': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/@nuxthub+core@0.8.27_db0@0.3.2_@libsql+client@0.15.9_better-sqlite3@11.10.0_drizzle-orm@0.44._oita7dv4ruuvcqadrtwvvu6voa/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/index.head').default>>>>
    }
    '/api/_hub/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/@nuxthub+core@0.8.27_db0@0.3.2_@libsql+client@0.15.9_better-sqlite3@11.10.0_drizzle-orm@0.44._oita7dv4ruuvcqadrtwvvu6voa/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/manifest.get').default>>>>
    }
    '/api/_hub/database/:command': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/@nuxthub+core@0.8.27_db0@0.3.2_@libsql+client@0.15.9_better-sqlite3@11.10.0_drizzle-orm@0.44._oita7dv4ruuvcqadrtwvvu6voa/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/[command].post').default>>>>
    }
    '/api/_hub/database/query': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/@nuxthub+core@0.8.27_db0@0.3.2_@libsql+client@0.15.9_better-sqlite3@11.10.0_drizzle-orm@0.44._oita7dv4ruuvcqadrtwvvu6voa/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/@nuxthub+core@0.8.27_db0@0.3.2_@libsql+client@0.15.9_better-sqlite3@11.10.0_drizzle-orm@0.44._oita7dv4ruuvcqadrtwvvu6voa/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/nuxt@3.17.5_@libsql+client@0.15.9_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@11._sukxntr3lfvlfbfzsu7xen76hm/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/@nuxt+icon@1.14.0_magicast@0.3.5_vite@7.0.0_@types+node@24.0.4_jiti@2.4.2_lightningcss@1.30.1_apytw4wby26tn4fmlef7tp6gwe/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}