// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.17.5_@libsql+client@0.15.9_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@11._sukxntr3lfvlfbfzsu7xen76hm/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.17.5_@libsql+client@0.15.9_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@11._sukxntr3lfvlfbfzsu7xen76hm/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.17.5_@libsql+client@0.15.9_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@11._sukxntr3lfvlfbfzsu7xen76hm/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.17.5_@libsql+client@0.15.9_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@11._sukxntr3lfvlfbfzsu7xen76hm/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.17.5_@libsql+client@0.15.9_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@11._sukxntr3lfvlfbfzsu7xen76hm/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.17.5_@libsql+client@0.15.9_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@11._sukxntr3lfvlfbfzsu7xen76hm/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.17.5_@libsql+client@0.15.9_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@11._sukxntr3lfvlfbfzsu7xen76hm/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.17.5_@libsql+client@0.15.9_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@11._sukxntr3lfvlfbfzsu7xen76hm/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.17.5_@libsql+client@0.15.9_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@11._sukxntr3lfvlfbfzsu7xen76hm/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_db0@0.3.2_@libsql+client@0.15.9_better-sqlite3@11.10.0_dr_q5jvzy7yc5h4mjqugs37rgl42e/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/@nuxt+icon@1.14.0_magicast@0.3.5_vite@7.0.0_@types+node@24.0.4_jiti@2.4.2_lightningcss@1.30.1_apytw4wby26tn4fmlef7tp6gwe/node_modules/@nuxt/icon/dist/runtime/plugin.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | '@nuxt/icon'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
